// ═══════════════════════════════════════════════════════
// LINEAR B DATA — verified against:
//   kinezika.com transliterator
//   Wikipedia Linear B + Mycenaean Greek articles
//   Ventris & Chadwick, Documents in Mycenaean Greek
//   Nakassis (2018) englianos.wordpress.com
//   Linear B Lexicon (Tselentis 2011)
//   PY Tn 316: Classical Inquiries (Woodard 2019)
// ═══════════════════════════════════════════════════════

const SIGNS = {
  'a':'𐀀','e':'𐀁','i':'𐀂','o':'𐀃','u':'𐀄',
  'da':'𐀅','de':'𐀆','di':'𐀇','do':'𐀈','du':'𐀉',
  'ja':'𐀊','je':'𐀋','jo':'𐀍',
  'ka':'𐀏','ke':'𐀐','ki':'𐀑','ko':'𐀒','ku':'𐀓',
  'ma':'𐀔','me':'𐀕','mi':'𐀖','mo':'𐀗','mu':'𐀘',
  'na':'𐀙','ne':'𐀚','ni':'𐀛','no':'𐀜','nu':'𐀝',
  'pa':'𐀞','pe':'𐀟','pi':'𐀠','po':'𐀡','pu':'𐀢',
  'qa':'𐀣','qe':'𐀤','qi':'𐀥','qo':'𐀦',
  'ra':'𐀨','re':'𐀩','ri':'𐀪','ro':'𐀫','ru':'𐀬',
  'sa':'𐀭','se':'𐀮','si':'𐀯','so':'𐀰','su':'𐀱',
  'ta':'𐀲','te':'𐀳','ti':'𐀴','to':'𐀵','tu':'𐀶',
  'wa':'𐀷','we':'𐀸','wi':'𐀹','wo':'𐀺',
  'za':'𐀼','ze':'𐀽','zo':'𐀿'
};

const SIGN_DETAILS = [
  {val:'a',sign:'𐀀',note:'Vowel. Very common word-initial sign.',ex:'a-to-ro-qo = anthrōpos (human being)'},
  {val:'e',sign:'𐀁',note:'Vowel. One of the highest-frequency signs.',ex:'e-ko = ekhō (to have)'},
  {val:'i',sign:'𐀂',note:'Vowel.',ex:'i-je-re-ja = hiereja (priestess)'},
  {val:'o',sign:'𐀃',note:'Vowel. Common in nominative endings.',ex:'o-no = onos (price, hire)'},
  {val:'u',sign:'𐀄',note:'Vowel.',ex:'u-po = hupo (under)'},
  {val:'da',sign:'𐀅',note:'d-series. Linear B distinguishes d from t.',ex:'da-mo = dāmos (community)'},
  {val:'de',sign:'𐀆',note:'d-series.',ex:'de-so-mo = desmos (bond)'},
  {val:'di',sign:'𐀇',note:'d-series.',ex:'di-we = Diwei (Zeus, dative)'},
  {val:'do',sign:'𐀈',note:'d-series.',ex:'do-e-ro = doelos (slave)'},
  {val:'du',sign:'𐀉',note:'d-series.',ex:'du-wo = dwō (two)'},
  {val:'ja',sign:'𐀊',note:'j-series. Palatal semivowel, like English "y".',ex:'ja-si-ja = iasia (place name)'},
  {val:'je',sign:'𐀋',note:'j-series.',ex:'i-je-re-u = iereus (priest)'},
  {val:'jo',sign:'𐀍',note:'j-series. U+1000C is unassigned.',ex:'a-te-mi-ti-jo = Artemitios'},
  {val:'ka',sign:'𐀏',note:'k-series. No voiced/aspirate distinction.',ex:'ka-ko = khalkos (bronze)'},
  {val:'ke',sign:'𐀐',note:'k-series.',ex:'ke-ra-me-u = kerameus (potter)'},
  {val:'ki',sign:'𐀑',note:'k-series.',ex:'ki-to = khitōn (tunic)'},
  {val:'ko',sign:'𐀒',note:'k-series.',ex:'ko-no-so = Knossos'},
  {val:'ku',sign:'𐀓',note:'k-series.',ex:'ku-ru-so = khrusos (gold)'},
  {val:'ma',sign:'𐀔',note:'m-series.',ex:'ma-te = mātēr (mother)'},
  {val:'me',sign:'𐀕',note:'m-series.',ex:'me-ri = meli (honey)'},
  {val:'mi',sign:'𐀖',note:'m-series.',ex:'mi-ra = moira (portion)'},
  {val:'mo',sign:'𐀗',note:'m-series.',ex:'mo-ro-qa = a title'},
  {val:'mu',sign:'𐀘',note:'m-series.',ex:'mu-ka-na = Mycenae'},
  {val:'na',sign:'𐀙',note:'n-series. Very common.',ex:'wa-na-ka = king (na is middle sign)'},
  {val:'ne',sign:'𐀚',note:'n-series.',ex:'ne-wa = newos (new)'},
  {val:'ni',sign:'𐀛',note:'n-series.',ex:'a-mi-ni-so = Amnissos'},
  {val:'no',sign:'𐀜',note:'n-series.',ex:'ko-no-so = Knossos (middle sign)'},
  {val:'nu',sign:'𐀝',note:'n-series.',ex:'nu-wa-ja = place name'},
  {val:'pa',sign:'𐀞',note:'p-series. Very high frequency.',ex:'pa-te = patēr (father)'},
  {val:'pe',sign:'𐀟',note:'p-series.',ex:'pe-ma = sperma (seed)'},
  {val:'pi',sign:'𐀠',note:'p-series.',ex:'pi-ri-je-te = priestly title'},
  {val:'po',sign:'𐀡',note:'p-series. po-se-da-o = Poseidon.',ex:'po-me = poimēn (shepherd)'},
  {val:'pu',sign:'𐀢',note:'p-series.',ex:'pu-ro = Pulos (Pylos)'},
  {val:'qa',sign:'𐀣',note:'q-series. Labio-velar kʷ — lost in later Greek.',ex:'qa-si-re-u → basileus'},
  {val:'qe',sign:'𐀤',note:'q-series. Labio-velar gʷe/kʷe.',ex:'ra-wa-ke-ta = army leader'},
  {val:'qi',sign:'𐀥',note:'q-series. Rare.',ex:'qi-si-pe-e = swords (dual)'},
  {val:'qo',sign:'𐀦',note:'q-series. Often relates to cattle (gʷous).',ex:'qo-u-ko-ro → boukoloi'},
  {val:'ra',sign:'𐀨',note:'r-series. Covers BOTH r and l sounds.',ex:'ra-wa-ke-ta = army leader'},
  {val:'re',sign:'𐀩',note:'r-series. r and l not distinguished.',ex:'e-re-u-te-ro = eleutheros (free)'},
  {val:'ri',sign:'𐀪',note:'r-series.',ex:'ti-ri-po = tripous (tripod)'},
  {val:'ro',sign:'𐀫',note:'r-series.',ex:'do-e-ro = slave (ends with ro)'},
  {val:'ru',sign:'𐀬',note:'r-series.',ex:'ku-ru-so = gold (echo vowel)'},
  {val:'sa',sign:'𐀭',note:'s-series.',ex:'sa-ra-pe-da = divine epithet'},
  {val:'se',sign:'𐀮',note:'s-series.',ex:'a-pi-po-re-we = amphorae'},
  {val:'si',sign:'𐀯',note:'s-series.',ex:'si-to = sitos (grain)'},
  {val:'so',sign:'𐀰',note:'s-series.',ex:'to-so = tosos (so much)'},
  {val:'su',sign:'𐀱',note:'s-series.',ex:'su-ko = sukon (fig)'},
  {val:'ta',sign:'𐀲',note:'t-series. Extremely common.',ex:'ta-ra-si-ja = wool allocation'},
  {val:'te',sign:'𐀳',note:'t-series. Covers t and th.',ex:'te-o = theos (god)'},
  {val:'ti',sign:'𐀴',note:'t-series.',ex:'ti-ri-po = tripous (tripod)'},
  {val:'to',sign:'𐀵',note:'t-series.',ex:'to-so = tosos (so much)'},
  {val:'tu',sign:'𐀶',note:'t-series.',ex:'tu-ka-te = thugater (daughter)'},
  {val:'wa',sign:'𐀷',note:'w-series. Digamma (Ϝ) — lost in later Greek.',ex:'wa-na-ka = wanaks (king)'},
  {val:'we',sign:'𐀸',note:'w-series.',ex:'ka-ke-we = bronze-smiths (plural)'},
  {val:'wi',sign:'𐀹',note:'w-series.',ex:'wi-ri-ne-jo = of leather'},
  {val:'wo',sign:'𐀺',note:'w-series.',ex:'we-ke = wergei (works on)'},
  {val:'za',sign:'𐀼',note:'z-series. Possibly ts/dz. za ≠ wa.',ex:'za-we-te = zawete (this year)'},
  {val:'ze',sign:'𐀽',note:'z-series.',ex:'ze-u-ke-si = zeugesi (pairs/yokes)'},
  {val:'zo',sign:'𐀿',note:'z-series. U+1003B and U+1003E unassigned.',ex:'zo-a = zōa (animals)'},
];

// ── TABLETS ─────────────────────────────────────────────
const TABLETS = {
  ta641:{
    ref:'PY Ta 641',name:'The Tripod Tablet',difficulty:'Beginner',
    date:'c.1180 BCE · Pylos · Scribe 2',
    desc:'The most famous Linear B tablet. Discovered by Blegen at Pylos in 1953 and sent immediately to Ventris — the match between words and vessel ideograms confirmed his decipherment. Records ritual feasting vessels.',
    lines:[
      {n:'.1',signs:'𐀴𐀪𐀡𐀆',translit:'ti-ri-po-de',ideogram:'TRIPOD 2',meaning:'Tripods of Cretan workmanship — 2'},
      {n:'.2',signs:'𐀴𐀪𐀃𐀸',translit:'ti-ri-o-we',ideogram:'TRIPOD 1',meaning:'Tripod with three handles — 1'},
      {n:'.3',signs:'𐀀𐀙𐀺𐀸',translit:'a-no-we',ideogram:'TRIPOD 1',meaning:'Tripod without handles — 1'},
      {n:'.4',signs:'𐀇𐀞',translit:'di-pa',ideogram:'VAS 2',meaning:'Cups/goblets (dipa) — 2'},
      {n:'.5',signs:'𐀇𐀞𐀕𐀍𐀡𐀳𐀫𐀸',translit:'di-pa me-zo-e qe-to-ro-we',ideogram:'VAS 1',meaning:'Larger cups with four handles — 1'},
      {n:'.6',signs:'𐀇𐀞𐀕𐀹𐀍𐀴𐀪𐀍𐀸',translit:'di-pa me-wi-jo ti-ri-jo-we',ideogram:'VAS 2',meaning:'Smaller cups with three handles — 2'},
      {n:'.7',signs:'𐀇𐀞𐀕𐀹𐀍𐀀𐀙𐀺𐀸',translit:'di-pa me-wi-jo a-no-we',ideogram:'VAS 1',meaning:'Smaller cup without handles — 1'},
    ]
  },
  cn608:{
    ref:'PY Cn 608',name:'The Pig-Fattening Tablet',difficulty:'Beginner',
    date:'c.1200 BCE · Pylos · Scribe 1',
    desc:'Records future pig-fattening across nine Pylian districts. The future tense verb — and the palace\'s subsequent destruction — means these pigs were probably never fattened. Translation: Nakassis (2018).',
    lines:[
      {n:'.1',signs:'𐀍𐀀𐀮𐀰𐀯',translit:'jo-a-se-so-si , si-a2-ro',ideogram:'',meaning:'"Thus will they fatten fatted pigs" — future tense header'},
      {n:'.2',signs:'𐀃𐀠𐀅𐀔𐀍',translit:'o-pi-da-mi-jo',ideogram:'',meaning:'"Community officials" (opidāmioi)'},
      {n:'.3',signs:'𐀠𐀿',translit:'pi-[*82]',ideogram:'SUS+SI 3',meaning:'Piswā — FATTED PIGS 3'},
      {n:'.4',signs:'𐀕𐀲𐀞',translit:'me-ta-pa',ideogram:'SUS+SI 3',meaning:'Metapā — FATTED PIGS 3'},
      {n:'.5',signs:'𐀟𐀵𐀜',translit:'pe-to-no',ideogram:'SUS+SI 6',meaning:'Pethnos — FATTED PIGS 6'},
      {n:'.6',signs:'𐀞𐀏𐀊𐀭',translit:'pa-ki-ja-si',ideogram:'SUS+SI 2',meaning:'Sphagiānes — FATTED PIGS 2'},
      {n:'.7',signs:'𐀀𐀢𐀸',translit:'a-pu2-we',ideogram:'SUS+SI 2',meaning:'Aphus — FATTED PIGS 2'},
      {n:'.8',signs:'𐀀𐀐𐀩𐀷',translit:'a-ke-re-wa',ideogram:'SUS+SI 2',meaning:'Agrēwā — FATTED PIGS 2'},
      {n:'.9',signs:'𐀁𐀨𐀲𐀁',translit:'e-ra-te-i',ideogram:'SUS+SI 3',meaning:'Elatos — FATTED PIGS 3'},
      {n:'.10',signs:'𐀏𐀨𐀅𐀫',translit:'ka-ra-do-ro',ideogram:'SUS+SI 2',meaning:'Kharadroi — FATTED PIGS 2'},
      {n:'.11',signs:'𐀪𐀍',translit:'ri-jo',ideogram:'SUS+SI 2',meaning:'Rhion — FATTED PIGS 2'},
    ]
  },
  fn7:{
    ref:'PY Fn 7',name:'The Oil Ration Tablet',difficulty:'Beginner',
    date:'c.1200 BCE · Pylos',
    desc:'Records olive oil allocations to the palace hierarchy. The most common tablet format: recipient + ideogram + quantity.',
    lines:[
      {n:'.1',signs:'𐀷𐀙𐀏',translit:'wa-na-ka',ideogram:'OIL [quantity]',meaning:'The wanax (king) — receives oil'},
      {n:'.2',signs:'𐀤𐀷𐀐𐀲',translit:'ra-wa-ke-ta',ideogram:'OIL [quantity]',meaning:'The lawāgetās (army leader) — receives oil'},
      {n:'.3',signs:'𐀁𐀨𐀺',translit:'e-ra-wo',ideogram:'',meaning:'"Olive oil" — the commodity'},
      {n:'.4',signs:'𐀵𐀰',translit:'to-so',ideogram:'OIL [total]',meaning:'to-so = "so much" — the total'},
    ]
  },
  tn316:{
    ref:'PY Tn 316',name:'The God Tablet',difficulty:'Intermediate',
    date:'c.1180 BCE · Pylos · Scribe 2',
    desc:'The most important religious Linear B document. Records offerings of gold vessels and persons (po-re-na) sent to shrines of multiple deities. Divided into four sections each opening with pu-ro (Pylos). Names Poseidon, Hera, Zeus, Athena, Dionysus, and others. Source: Trzaskoma (2004); Woodard, Classical Inquiries (2019).',
    lines:[
      {n:'v.1',signs:'𐀢𐀫',translit:'pu-ro',ideogram:'',meaning:'PYLOS — section header (repeated 4 times across the tablet)'},
      {n:'v.2',signs:'𐀍𐀁',translit:'i-je-to-qe',ideogram:'',meaning:'"And a procession goes to the sanctuary" — ritual action verb'},
      {n:'v.3',signs:'𐀡𐀮𐀅𐀃𐀚',translit:'po-se-da-o-ne',ideogram:'AUR VAS 1, VIR 1',meaning:'To Poseidon — gold vessel ×1, man ×1'},
      {n:'v.4',signs:'𐀆𐀷𐀞𐀳',translit:'do-ra-qe pe-re',ideogram:'',meaning:'"And he carries gifts" — the standard offering formula'},
      {n:'v.5',signs:'𐀁𐀨',translit:'e-ra',ideogram:'AUR VAS 1, MUL 1',meaning:'To Hera — gold vessel ×1, woman ×1'},
      {n:'v.6',signs:'𐀇𐀺𐀙𐀄𐀰',translit:'di-wo-nu-so',ideogram:'AUR VAS 1',meaning:'To Dionysos — gold vessel ×1 (one of his earliest known attestations)'},
      {n:'v.7',signs:'𐀇𐀸',translit:'di-we',ideogram:'AUR VAS 1, VIR 1',meaning:'To Zeus — gold vessel ×1, man ×1'},
      {n:'v.8',signs:'𐀀𐀲𐀙𐀡𐀳𐀹𐀊',translit:'a-ta-na po-ti-ni-ja',ideogram:'AUR VAS 1',meaning:'To Athena Potnia ("Mistress Athena") — gold vessel ×1'},
      {n:'v.9',signs:'𐀁𐀪𐀙𐀄',translit:'e-ri-nu',ideogram:'AUR VAS 1',meaning:'To the Erinys (Fury/Furies) — gold vessel ×1'},
      {n:'v.10',signs:'𐀕𐀏',translit:'ma-ka',ideogram:'AUR VAS 1',meaning:'To Ma-ka ("Mother Earth"? — identification debated) — gold vessel ×1'},
    ]
  },
  jn829:{
    ref:'PY Jn 829',name:'The Bronze-Smiths Tablet',difficulty:'Intermediate',
    date:'c.1200 BCE · Pylos',
    desc:'One of the Jn series — the most detailed bronze-working records in the corpus. Lists bronze allocated to individual smiths (ka-ke-we) across Pylian districts. The palace was clearly mobilising metal urgently before its destruction.',
    lines:[
      {n:'.1',signs:'𐀏𐀐𐀸',translit:'ka-ke-we',ideogram:'',meaning:'"Bronze-smiths" — subject of the tablet'},
      {n:'.2',signs:'𐀃𐀠𐀅𐀔𐀍',translit:'o-pi-da-mi-jo',ideogram:'',meaning:'"Community officials" overseeing the smiths'},
      {n:'.3',signs:'𐀏𐀏',translit:'ka-ko',ideogram:'AES [weight]',meaning:'Bronze — with a weight in Mycenaean units (AES = Latin for bronze)'},
      {n:'.4',signs:'𐀸𐀐',translit:'we-ke',ideogram:'',meaning:'"wergei" — works on / is working (craftsman formula)'},
      {n:'.5',signs:'𐀀𐀙𐀃𐀸',translit:'a-no-qo-ta',ideogram:'AES 2',meaning:'Anokhwotās (a smith\'s name) — bronze 2 units'},
      {n:'.6',signs:'𐀵𐀰',translit:'to-so',ideogram:'AES [total]',meaning:'to-so = total bronze allocated'},
    ]
  },
  kn_fp1:{
    ref:'KN Fp(1) 1',name:'The Monthly Oil Tablet (Knossos)',difficulty:'Advanced',
    date:'c.1375 BCE · Knossos (older than all Pylos tablets)',
    desc:'From the Knossos Fp series — monthly records of olive oil to deities and sanctuaries. pa-si-te-o-i = "to all the gods" (dative plural) is the key formula. Translation: Mycenaean Miscellany (2018).',
    lines:[
      {n:'.1',signs:'𐀏𐀨𐀁𐀪𐀍',translit:'ka-ra-e-ri-jo',ideogram:'',meaning:'In the month of Karaeriōn (a calendar month name)'},
      {n:'.2',signs:'𐀞𐀯𐀳𐀃𐀂',translit:'pa-si-te-o-i',ideogram:'OIL 9.6L',meaning:'"To all the gods" (pansi theohoi, dat. pl.) — oil 9.6 litres'},
      {n:'.3',signs:'𐀤𐀨𐀭𐀊',translit:'qe-ra-si-ja',ideogram:'OIL 9.6L',meaning:'To Qerasija (divine title, possibly linked to Artemis) — 9.6L'},
      {n:'.4',signs:'𐀵𐀰',translit:'to-so',ideogram:'OIL [total]',meaning:'Total oil disbursed this month'},
    ]
  },
  py_an1:{
    ref:'PY An 1',name:'The Coast Guard Tablet',difficulty:'Advanced',
    date:'c.1180 BCE · Pylos',
    desc:'The first "o-ka" (coast guard) tablet — records military contingents defending the Pylian coastline. Unusually narrative for Linear B. The urgency suggests the palace anticipated attack. Source: Mnamon, SNS Pisa.',
    lines:[
      {n:'.1',signs:'𐀃𐀏',translit:'o-ka',ideogram:'',meaning:'"o-ka" — the military unit / watch command (exact meaning debated)'},
      {n:'.2',signs:'𐀁𐀐𐀲',translit:'e-ke-ta',ideogram:'',meaning:'e-ke-ta = "follower/companion" — a military title (hekwetās)'},
      {n:'.3',signs:'𐀣𐀫𐀏𐀍',translit:'qa-ra-ko-ro',ideogram:'VIR 10',meaning:'Khalarkhos (commander name) — MEN 10'},
      {n:'.4',signs:'𐀃𐀪𐀕𐀍',translit:'o-ri-me-no',ideogram:'VIR 30',meaning:'Orimenos (commander) — MEN 30'},
      {n:'.5',signs:'𐀉𐀺𐀍𐀃',translit:'du-wo-jo-o',ideogram:'VIR 20',meaning:'Dwoyos (commander) — MEN 20'},
      {n:'.6',signs:'𐀵𐀰',translit:'to-so',ideogram:'VIR [total]',meaning:'Total men assigned to coastal defence'},
    ]
  }
};

// ── TRANSLATION DICTIONARY ────────────────────────────────
// Maps English / Greek words → attested Mycenaean words
// Sources: Tselentis Linear B Lexicon (2011); Wikipedia Mycenaean Greek
const TRANSLATION_DICT = [
  {en:['king','ruler','lord'],gr:['βασιλιάς','ἄναξ','άναξ','anax'],fr:['roi','seigneur'],myc:'wa-na-ka',meaning:'wanax (supreme king)',note:'The Mycenaean king. qa-si-re-u was a subordinate — only later did it mean "king".'},
  {en:['chieftain','chief','local king','basileus'],gr:['βασιλεύς','αρχηγός'],fr:['chef','chef local'],myc:'qa-si-re-u',meaning:'kʷasileús (local chieftain)',note:'Subordinate official → later "king" (basileus).'},
  {en:['army leader','general','warlord','commander'],gr:['στρατηγός','αρχηγός στρατού'],fr:['chef d\'armée','général'],myc:'ra-wa-ke-ta',meaning:'lawāgetās (leader of the army)',note:'Second-highest title at Pylos and Knossos.'},
  {en:['slave','servant','serf'],gr:['δοῦλος','σκλάβος','δούλος'],fr:['esclave','serviteur'],myc:'do-e-ro',meaning:'doelos (male slave)',note:'do-e-ra is the female form. Hundreds in palace records.'},
  {en:['priestess'],gr:['ἱέρεια','ιέρεια'],fr:['prêtresse'],myc:'i-je-re-ja',meaning:'hiereja (priestess)',note:'High-status women holding land and receiving rations.'},
  {en:['priest'],gr:['ἱερεύς','ιερέας'],fr:['prêtre'],myc:'i-je-re-u',meaning:'iereus (priest)',note:'Male priestly title.'},
  {en:['shepherd','herdsman','cowherd'],gr:['ποιμήν','βοσκός'],fr:['berger','pasteur'],myc:'po-me',meaning:'poimēn (shepherd)',note:'Very common in livestock records.'},
  {en:['potter'],gr:['κεραμεύς','αγγειοπλάστης'],fr:['potier'],myc:'ke-ra-me-u',meaning:'kerameus (potter)',note:'One of many craft titles.'},
  {en:['free','free man','free person','freeman'],gr:['ἐλεύθερος','ελεύθερος'],fr:['libre','homme libre'],myc:'e-re-u-te-ro',meaning:'eleutheros (free person)',note:'Contrasts with do-e-ro (slave).'},
  {en:['father'],gr:['πατέρας','πατήρ','baba'],fr:['père'],myc:'pa-te',meaning:'patēr (father)',note:'Final -r dropped (scribal rule 1).'},
  {en:['mother'],gr:['μητέρα','μήτηρ','mama','μαμά'],fr:['mère'],myc:'ma-te',meaning:'mātēr (mother)',note:'Attested in personal names and dedications.'},
  {en:['daughter'],gr:['κόρη','θυγάτηρ'],fr:['fille'],myc:'tu-ka-te',meaning:'thugater (daughter)',note:'Final -r dropped. Cluster th- written tu-.'},
  {en:['son','boy','young man'],gr:['γιος','υιός','κούρος'],fr:['fils','garçon'],myc:'ko-wo',meaning:'korwos (boy/son)',note:'Ancestor of κοῦρος (kouros).'},
  {en:['woman','lady'],gr:['γυναίκα','γυνή'],fr:['femme'],myc:'ku-na-ja',meaning:'kunāja (woman)',note:'Feminine adjectival form.'},
  {en:['god','deity'],gr:['θεός','θεά'],fr:['dieu','déesse'],myc:'te-o',meaning:'theos (god)',note:'te-sign covers t and th. PY Tn 316 names many gods.'},
  {en:['mistress','lady goddess','potnia'],gr:['πότνια','δέσποινα'],fr:['maîtresse','dame'],myc:'po-ti-ni-ja',meaning:'potnia (mistress, lady)',note:'"Potnia" is a title applied to several goddesses. po-ti-ni-ja a-ta-na = Mistress Athena.'},
  {en:['poseidon'],gr:['ποσειδών','ποσειδώνας'],fr:['poséidon'],myc:'po-se-da-o',meaning:'Poseidaōn',note:'Chief god at Pylos. PY Tn 316.'},
  {en:['zeus'],gr:['ζεύς','δίας'],fr:['zeus'],myc:'di-we',meaning:'Diwei (Zeus, dative)',note:'PY Tn 316. Nominative would be di-u.'},
  {en:['athena','athene'],gr:['αθηνά','αθήνη'],fr:['athéna'],myc:'a-ta-na',meaning:'Atana (Athena)',note:'a-ta-na po-ti-ni-ja = "Mistress Athena". PY Tn 316.'},
  {en:['hera'],gr:['ήρα'],fr:['héra'],myc:'e-ra',meaning:'Hera',note:'PY Tn 316. One of the earliest attestations.'},
  {en:['dionysus','dionysos','bacchus'],gr:['διόνυσος'],fr:['dionysos','bacchus'],myc:'di-wo-nu-so',meaning:'Diwonusos (Dionysus)',note:'One of the earliest attestations of this god\'s name anywhere.'},
  {en:['sacred land','sacred precinct','temenos','shrine'],gr:['τέμενος','ιερό'],fr:['terrain sacré','téménos'],myc:'te-me-no',meaning:'temenos (sacred land plot)',note:'Held by wanax and lawāgetās. Passed into Homer.'},
  {en:['grain','wheat','bread','cereal'],gr:['σιτάρι','σίτος','ψωμί'],fr:['grain','blé','céréale'],myc:'si-to',meaning:'sitos (grain/wheat)',note:'The most recorded commodity in all Linear B archives.'},
  {en:['oil','olive oil'],gr:['λάδι','έλαιο','ἔλαιον'],fr:['huile','huile d\'olive'],myc:'e-ra-wo',meaning:'elaiwon (olive oil)',note:'Second dominant commodity. r/l rule: ela- → e-ra-.'},
  {en:['honey'],gr:['μέλι'],fr:['miel'],myc:'me-ri',meaning:'meli (honey)',note:'r/l rule: meli → me-ri.'},
  {en:['wine'],gr:['κρασί','οἶνος','οίνος'],fr:['vin'],myc:'wo-no',meaning:'woinos (wine)',note:'Ancestor of οἶνος. wo- = digamma Ϝ.'},
  {en:['fig','figs'],gr:['σύκο','σῦκον'],fr:['figue'],myc:'su-ko',meaning:'sukon (fig)',note:'Ration and offering records.'},
  {en:['bronze','copper'],gr:['χαλκός','μπρούτζος','χαλκος'],fr:['bronze','cuivre'],myc:'ka-ko',meaning:'khalkos (bronze/copper)',note:'k-sign covers kh. Final -s dropped. PY Jn series.'},
  {en:['gold'],gr:['χρυσός','χρυσάφι'],fr:['or'],myc:'ku-ru-so',meaning:'khrusos (gold)',note:'khr- → ku-ru- (echo-vowel rule).'},
  {en:['wool','fleece'],gr:['μαλλί','ἔριον'],fr:['laine'],myc:'ta-ra-si-ja',meaning:'talasia (wool-working allocation)',note:'Core of the Mycenaean textile industry.'},
  {en:['tripod'],gr:['τρίποδας','τρίπους'],fr:['trépied'],myc:'ti-ri-po',meaning:'tripous (tripod)',note:'PY Ta 641. The key word of the decipherment.'},
  {en:['sword','swords','blade'],gr:['σπαθί','ξίφος'],fr:['épée','glaive'],myc:'qi-si-pe-e',meaning:'kʷsiphee (swords, dual)',note:'qi- = labio-velar kʷ.'},
  {en:['helmet'],gr:['κράνος','κόρυς'],fr:['casque'],myc:'ko-ru',meaning:'korus (helmet)',note:'Armour inventory tablets.'},
  {en:['pylos'],gr:['πύλος'],fr:['pylos'],myc:'pu-ro',meaning:'Pulos (Pylos)',note:'Palace of Nestor. 1107 tablets.'},
  {en:['knossos'],gr:['κνωσός'],fr:['cnossos'],myc:'ko-no-so',meaning:'Knossos',note:'3369 tablets. Largest archive.'},
  {en:['community','people','district','folk'],gr:['δήμος','κοινότητα','λαός'],fr:['communauté','peuple','district'],myc:'da-mo',meaning:'dāmos (community/district)',note:'Ancestor of classical dēmos.'},
  {en:['seed'],gr:['σπόρος','σπέρμα'],fr:['graine','semence'],myc:'pe-ma',meaning:'sperma (seed)',note:'sp- dropped (scribal rule 9).'},
  {en:['year','this year'],gr:['χρόνος','έτος','φέτος'],fr:['an','année'],myc:'za-we-te',meaning:'zawete (this year)',note:'za-sign is z/ts. The only attested "year" expression.'},
  {en:['total','so much','so many','sum'],gr:['σύνολο','τόσα','τόσο'],fr:['total','autant','somme'],myc:'to-so',meaning:'tosos (so much/many)',note:'Introduces totals on accounting tablets.'},
  {en:['new'],gr:['νέος','καινούριος'],fr:['nouveau','neuf'],myc:'ne-wa',meaning:'newos (new)',note:'Mycenaean form; Attic neos.'},
  {en:['all','every','everyone'],gr:['όλος','πᾶς','πάντα'],fr:['tout','tous'],myc:'pa-si',meaning:'pansi (to all, dative)',note:'pa-si-te-o-i = "to all the gods".'},
  {en:['field','land'],gr:['χωράφι','ἀγρός','γη'],fr:['champ','terre'],myc:'a-ko-ro',meaning:'agros (field)',note:'Land tenure records are among the most complex Linear B texts.'},
];

// ── DECODE WORDS ────────────────────────────────────────
const DECODE_WORDS = [
  {sylls:['wa','na','ka'],translit:'wa-na-ka',meaning:'King (wanax)',classical:'ἄναξ',tablet:'PY Er 312 + many',note:'Supreme ruler. wa-na-ka-te-ro = "of the king" also attested.'},
  {sylls:['qa','si','re','u'],translit:'qa-si-re-u',meaning:'Local chieftain → basileus',classical:'βασιλεύς',tablet:'PY Un 718',note:'Subordinate official. kʷ- evolved to b-.'},
  {sylls:['ra','wa','ke','ta'],translit:'ra-wa-ke-ta',meaning:'Army leader',classical:'λαϝαγέτας',tablet:'PY Er 312',note:'Second in rank. Temenos one-third the king\'s.'},
  {sylls:['si','to'],translit:'si-to',meaning:'Grain / wheat (sitos)',classical:'σῖτος',tablet:'Hundreds',note:'The most recorded commodity.'},
  {sylls:['ka','ko'],translit:'ka-ko',meaning:'Bronze (khalkos)',classical:'χαλκός',tablet:'PY Jn series',note:'k-sign covers kh. Final -s dropped. Verified.'},
  {sylls:['me','ri'],translit:'me-ri',meaning:'Honey (meli)',classical:'μέλι',tablet:'PY Un 267',note:'r/l rule: meli → me-ri.'},
  {sylls:['te','o'],translit:'te-o',meaning:'God (theos)',classical:'θεός',tablet:'PY Tn 316',note:'te covers t and th. PY Tn 316.'},
  {sylls:['pa','te'],translit:'pa-te',meaning:'Father (patēr)',classical:'πατήρ',tablet:'PY Ep 704',note:'Final -r dropped.'},
  {sylls:['do','e','ro'],translit:'do-e-ro',meaning:'Male slave',classical:'δοῦλος',tablet:'PY Aa, Ab series',note:'do-e-ra = female form.'},
  {sylls:['ku','ru','so'],translit:'ku-ru-so',meaning:'Gold (khrusos)',classical:'χρυσός',tablet:'PY Ta 714',note:'khr- → ku-ru- (echo-vowel rule).'},
  {sylls:['ko','no','so'],translit:'ko-no-so',meaning:'Knossos',classical:'Κνωσός',tablet:'KN series',note:'Double-s reduced to single.'},
  {sylls:['ti','ri','po'],translit:'ti-ri-po',meaning:'Tripod (tripous)',classical:'τρίπους',tablet:'PY Ta 641',note:'The word that proved the decipherment.'},
  {sylls:['pu','ro'],translit:'pu-ro',meaning:'Pylos',classical:'Πύλος',tablet:'PY series',note:'1107 tablets survive.'},
  {sylls:['e','ra','wo'],translit:'e-ra-wo',meaning:'Olive oil',classical:'ἔλαιον',tablet:'PY Fr series',note:'ela- → e-ra- (r/l rule). -wo = digamma.'},
  {sylls:['da','mo'],translit:'da-mo',meaning:'Community (dāmos)',classical:'δῆμος',tablet:'PY Eb, Ep series',note:'Ancestor of classical dēmos.'},
  {sylls:['i','je','re','ja'],translit:'i-je-re-ja',meaning:'Priestess',classical:'ἱέρεια',tablet:'PY Ep 704',note:'Named individually in tablets.'},
  {sylls:['pe','ma'],translit:'pe-ma',meaning:'Seed (sperma)',classical:'σπέρμα',tablet:'PY Er 312',note:'sp- dropped (scribal rule 9).'},
  {sylls:['po','me'],translit:'po-me',meaning:'Shepherd (poimēn)',classical:'ποιμήν',tablet:'PY Cn series',note:'po-me-ne = dative form.'},
  {sylls:['to','so'],translit:'to-so',meaning:'Total (tosos)',classical:'τόσος',tablet:'Hundreds',note:'Introduces totals.'},
  {sylls:['di','we'],translit:'di-we',meaning:'Zeus (dative)',classical:'Διΐ',tablet:'PY Tn 316',note:'di-wo-nu-so = Dionysus also attested.'},
];

// ── VOCABULARY ──────────────────────────────────────────
const VOCAB = [
  // ── TITLES & OFFICIALS ───────────────────────────────
  {sylls:['wa','na','ka'],translit:'wa-na-ka',meaning:'King (wanax)',classical:'ἄναξ',domain:'Titles',
   detail:'The supreme ruler. One wanax per palace. wa-na-ka-te-ro = "of the wanax" (adjective, also attested). wa-na-ka-te = dative. Attested at Pylos, Knossos, Mycenae, Thebes.'},
  {sylls:['ra','wa','ke','ta'],translit:'ra-wa-ke-ta',meaning:'Army leader (lawāgetās)',classical:'λαϝαγέτας',domain:'Titles',
   detail:'Second-highest title after the wanax. Held a temenos one-third the size of the king\'s. Attested PY Er 312. The -w- is the digamma (Ϝ) — lawos = army/people.'},
  {sylls:['qa','si','re','u'],translit:'qa-si-re-u',meaning:'Local chieftain',classical:'βασιλεύς',domain:'Titles',
   detail:'A subordinate official — possibly a craftsman overseer (Palmer) or local headman. After the palace collapse, rose to mean "king". The labio-velar qw- became b- in later Greek.'},
  {sylls:['da','mo','ko','ro'],translit:'da-mo-ko-ro',meaning:'District officer (damokoros)',classical:'δημοκόρος',domain:'Titles',
   detail:'A local official managing the dāmos (district). Literally "one who tends/sweeps the community". Attested when the king appoints one: "wa-na-ka te-ke au-ke-wa da-mo-ko-ro" (PY).'},
  {sylls:['te','re','ta'],translit:'te-re-ta',meaning:'Holder of a te-re-ta (land tenure title)',classical:'τελεστής',domain:'Titles',
   detail:'A landholding official below the qa-si-re-u. In the Er series at Pylos, te-re-ta-o (genitive plural) = "of the telestai" — they hold land in the temenos system. PY Er 312.'},
  {sylls:['e','qe','ta'],translit:'e-qe-ta',meaning:'Follower / companion (hekwetās)',classical:'ἑπέτης',domain:'Titles',
   detail:'A military companion or "follower" attached to a commander. The e-qe-ta appear in the o-ka (coast guard) tablets at Pylos alongside troop numbers. PY An series.'},
  {sylls:['ko','re','te'],translit:'ko-re-te',meaning:'Village mayor (koreter)',classical:'κορητήρ',domain:'Titles',
   detail:'The head official of a Pylian district town. Each district had a ko-re-te and a po-ro-ko-re-te (deputy). Attested across the Ma series at Pylos.'},
  // ── SOCIETY ──────────────────────────────────────────
  {sylls:['da','mo'],translit:'da-mo',meaning:'Community / district (dāmos)',classical:'δῆμος',domain:'Society',
   detail:'A semi-independent local institution managing land allocation and agricultural tasks. Ancestor of the classical dēmos. The da-mo-ko-ro was its official overseer.'},
  {sylls:['do','e','ro'],translit:'do-e-ro',meaning:'Male slave (doelos)',classical:'δοῦλος',domain:'Society',
   detail:'do-e-ra is the female form. Hundreds listed in palace workforce records (Aa/Ab series) with their rations and craft assignments. The word → δοῦλος in classical Greek.'},
  {sylls:['do','e','ra'],translit:'do-e-ra',meaning:'Female slave (doelā)',classical:'δούλη',domain:'Society',
   detail:'Female counterpart of do-e-ro. Appears with ko-wa (girls) and ko-wo (boys) in records of dependent workers. Some do-e-ra are attached to specific sanctuaries.'},
  {sylls:['e','re','u','te','ro'],translit:'e-re-u-te-ro',meaning:'Free person (eleutheros)',classical:'ἐλεύθερος',domain:'Society',
   detail:'Status term contrasting with do-e-ro (slave). The r/l rule applies twice: ele- → e-re-, and the internal -l- → -r-. Fundamental social distinction in palace records.'},
  {sylls:['ko','wo'],translit:'ko-wo',meaning:'Boy (korwos)',classical:'κοῦρος',domain:'Society',
   detail:'Appears alongside ko-wa (girl) in workforce and population records. The ancestor of κοῦρος — the famous Archaic Greek sculpture type. ko-wa is the feminine form.'},
  {sylls:['ko','wa'],translit:'ko-wa',meaning:'Girl (korwā)',classical:'κόρη',domain:'Society',
   detail:'Female counterpart of ko-wo. These appear in records like "ko-wa 3 ko-wo 7" — 3 girls, 7 boys — in workforce tallies. Ancestor of κόρη (kore).'},
  {sylls:['pa','te'],translit:'pa-te',meaning:'Father (patēr)',classical:'πατήρ',domain:'Society',
   detail:'Final -r dropped (scribal rule 1). Used in personal name compounds and social descriptions. The same word passed unchanged into Latin pater and English "father".'},
  {sylls:['ma','te'],translit:'ma-te',meaning:'Mother (mātēr)',classical:'μήτηρ',domain:'Society',
   detail:'Final -r dropped. Attested in personal names and dedications. The direct ancestor of Latin mater and English "mother".'},
  {sylls:['tu','ka','te'],translit:'tu-ka-te',meaning:'Daughter (thugater)',classical:'θυγάτηρ',domain:'Society',
   detail:'Cluster th- written tu- (echo-vowel rule), final -r dropped. Survives into classical Greek as θυγάτηρ, and cognate with English "daughter".'},
  {sylls:['a','to','ro','qo'],translit:'a-to-ro-qo',meaning:'Human being (anthrōpos)',classical:'ἄνθρωπος',domain:'Society',
   detail:'The nasal before consonant is dropped (rule 2): anthr- → a-to-ro-. The qo = labio-velar qw (later -pos). The ancestor of "anthropology". Attested on several tablets.'},
  // ── RELIGION ─────────────────────────────────────────
  {sylls:['i','je','re','ja'],translit:'i-je-re-ja',meaning:'Priestess (hiereja)',classical:'ἱέρεια',domain:'Religion',
   detail:'One of the highest-status roles for women. Priestesses held land, received rations, and are named individually. PY Ep 704 names a specific priestess holding land "of the god".'},
  {sylls:['i','je','re','u'],translit:'i-je-re-u',meaning:'Priest (iereus)',classical:'ἱερεύς',domain:'Religion',
   detail:'Male priestly title. i-je-ro = "sacred, holy" (hieron). Attested in land and offering records. The base for "hierarchy", "hieroglyph", and "Jerusalem".'},
  {sylls:['te','o'],translit:'te-o',meaning:'God (theos)',classical:'θεός',domain:'Religion',
   detail:'The te-sign covers both t- and th-. PY Tn 316 names at least 10 deities. pa-si-te-o-i = "to all the gods" (dative plural, KN Fp series).'},
  {sylls:['po','ti','ni','ja'],translit:'po-ti-ni-ja',meaning:'Mistress / Lady (Potnia)',classical:'πότνια',domain:'Religion',
   detail:'A divine title applied to several goddesses, not one deity. a-ta-na po-ti-ni-ja = Mistress Athena; i-qe-ja po-ti-ni-ja = Mistress of the Horses. PY Tn 316.'},
  {sylls:['po','se','da','o'],translit:'po-se-da-o',meaning:'Poseidon',classical:'Ποσειδῶν',domain:'Religion',
   detail:'The chief god at Pylos — receives the largest offerings on PY Tn 316. Also attested as "Poseidon of Srapedas" (PY Un 718). His prominence at Pylos predates Olympian religion.'},
  {sylls:['di','we'],translit:'di-we',meaning:'Zeus (dative: Diwei)',classical:'Διΐ',domain:'Religion',
   detail:'The dative case of di-u (Zeus). Attested on PY Tn 316. di-wo-nu-so = Dionysus is also on that tablet, one of the earliest attestations of his name anywhere.'},
  {sylls:['di','wo','nu','so'],translit:'di-wo-nu-so',meaning:'Dionysus',classical:'Διόνυσος',domain:'Religion',
   detail:'One of the earliest attestations of this god\'s name. Receives a gold vessel on PY Tn 316. His Mycenaean presence undermines the theory that Dionysus was a late foreign import.'},
  {sylls:['a','ta','na'],translit:'a-ta-na',meaning:'Athena',classical:'Ἀθηνᾶ',domain:'Religion',
   detail:'a-ta-na po-ti-ni-ja = "Mistress Athena". PY Tn 316. The -th- written as ta- (no aspiration distinction). Already a major deity in the Bronze Age.'},
  {sylls:['e','ra'],translit:'e-ra',meaning:'Hera',classical:'Ἥρα',domain:'Religion',
   detail:'Receives a gold vessel and a woman offering on PY Tn 316. One of the earliest attestations of her name. Her cult at Pylos predates the Olympian pantheon as commonly understood.'},
  {sylls:['a','re'],translit:'a-re',meaning:'Ares',classical:'Ἄρης',domain:'Religion',
   detail:'Attested on KN V 52 and possibly Tn 316. Final -s dropped. The god of war already present in the Mycenaean pantheon, though less prominent than Poseidon.'},
  {sylls:['e','ri','nu'],translit:'e-ri-nu',meaning:'Erinys (Fury)',classical:'Ἐρινύς',domain:'Religion',
   detail:'Receives a gold vessel on PY Tn 316. The Furies — goddesses of vengeance — were thus already worshipped in the Bronze Age. Final -s dropped (e-ri-nu < Erinys).'},
  // ── COMMODITIES ──────────────────────────────────────
  {sylls:['si','to'],translit:'si-to',meaning:'Grain / wheat (sitos)',classical:'σῖτος',domain:'Commodities',
   detail:'The most-recorded commodity across all sites. Measured in dry units T, V, Z. Appears alongside the WHEAT ideogram in thousands of tablet lines.'},
  {sylls:['e','ra','wo'],translit:'e-ra-wo',meaning:'Olive oil (elaiwon)',classical:'ἔλαιον',domain:'Commodities',
   detail:'The second dominant commodity. Perfumed oils with coriander (ko-ri-ja-da-na), rose, and sage were a major export. The -wo marks the digamma: elaiFon.'},
  {sylls:['me','ri'],translit:'me-ri',meaning:'Honey (meli)',classical:'μέλι',domain:'Commodities',
   detail:'Recording in offerings and perfumes. Attested PY Un 267. The r/l rule: meli → me-ri. "Mead" (fermented honey drink) likely also existed.'},
  {sylls:['wo','no'],translit:'wo-no',meaning:'Wine (woinos)',classical:'οἶνος',domain:'Commodities',
   detail:'wo- = digamma (Ϝ): woinos. The ancestor of οἶνος and Latin vinum. Appears in offering records alongside grain and oil. PY Un 718 records wine for Poseidon.'},
  {sylls:['ka','ko'],translit:'ka-ko',meaning:'Bronze / copper (khalkos)',classical:'χαλκός',domain:'Commodities',
   detail:'The PY Jn series tracks every unit of bronze in the kingdom. The k-sign covers kh — khalkos correctly → ka-ko. Final -s dropped. The word survives in "chalcolithic".'},
  {sylls:['ku','ru','so'],translit:'ku-ru-so',meaning:'Gold (khrusos)',classical:'χρυσός',domain:'Commodities',
   detail:'Echo-vowel rule: khr- → ku-ru-. Vessel inventories and divine offerings. Survives in English "chrysanthemum" (golden flower) and "chrysalis".'},
  {sylls:['a','re','ku','te','ra'],translit:'a-re-ku-te-ra',meaning:'Silver vessel? (argurotēra)',classical:'ἀργυρός',domain:'Commodities',
   detail:'Possibly derived from arguros (silver). Context in vessel inventories. Silver is less frequently recorded than gold in the tablets.'},
  {sylls:['ri','no'],translit:'ri-no',meaning:'Flax / linen (linon)',classical:'λίνον',domain:'Commodities',
   detail:'ri-no = linon (flax, linen). r/l rule: li- → ri-. Appears in textile records. The Mycenaean textile industry was enormous — linen alongside wool.'},
  {sylls:['ta','ra','si','ja'],translit:'ta-ra-si-ja',meaning:'Wool allocation (talasia)',classical:'ταλασία',domain:'Commodities',
   detail:'The ta-ra-si-ja system was the core of the Mycenaean textile industry. Workers received wool allocations and owed finished cloth in return. Hundreds of records.'},
  {sylls:['su','ko'],translit:'su-ko',meaning:'Fig (sukon)',classical:'σῦκον',domain:'Commodities',
   detail:'Figs recorded in ration and offering lists. PY Un 267. The direct ancestor of σῦκον and Latin ficus. Figs were a significant part of the Bronze Age diet.'},
  {sylls:['ko','ri','ja','da','na'],translit:'ko-ri-ja-da-na',meaning:'Coriander (koriandron)',classical:'κορίανδρον',domain:'Commodities',
   detail:'Attested in perfumed oil records. One of the spices added to olive oil for export. The word "coriander" is ultimately borrowed from this Mycenaean form.'},
  // ── OBJECTS & EQUIPMENT ──────────────────────────────
  {sylls:['ti','ri','po'],translit:'ti-ri-po',meaning:'Tripod (tripous)',classical:'τρίπους',domain:'Objects',
   detail:'PY Ta 641. The word that proved the decipherment — Ventris saw ti-ri-po next to a tripod drawing. Echo-vowel rule: tri- → ti-ri-. tri = three, pous = foot.'},
  {sylls:['di','pa'],translit:'di-pa',meaning:'Cup / goblet (depas)',classical:'δέπας',domain:'Objects',
   detail:'Attested on PY Ta 641. δέπας is a Homeric word for a drinking vessel (Iliad 11.632). The Linear B di-pa confirms this archaic vocabulary was in everyday Mycenaean use.'},
  {sylls:['ko','ru'],translit:'ko-ru',meaning:'Helmet (korus)',classical:'κόρυς',domain:'Objects',
   detail:'Appears in armour inventory tablets. Detailed records list components: base, cheekpieces, crest holder. The Mycenaean "boar\'s tusk helmet" is archaeologically well attested.'},
  {sylls:['to','ra','ke'],translit:'to-ra-ke',meaning:'Breastplates (thōrākes)',classical:'θώρακες',domain:'Objects',
   detail:'Plural of thōrāx (breastplate). Detailed armour inventories at Pylos and Knossos list each component. The same word later shifted to mean "chest/thorax" anatomically.'},
  {sylls:['a','ni','ja'],translit:'a-ni-ja',meaning:'Reins (hāniai)',classical:'ἡνία',domain:'Objects',
   detail:'hāniai = reins. Initial h- not written (scribal convention). Appears in chariot records. a-ni-ja-pi = "with reins" (instrumental plural). KN series.'},
  {sylls:['i','qi','ja'],translit:'i-qi-ja',meaning:'Chariot (hikkʷia)',classical:'ἱππεία',domain:'Objects',
   detail:'The chariot is one of the best-documented items in Linear B. qi = labio-velar kʷ. KN Sc series contains hundreds of chariot records with wheel, body, and harness components.'},
  {sylls:['to','pe','za'],translit:'to-pe-za',meaning:'Table (torpedza)',classical:'τράπεζα',domain:'Objects',
   detail:'Attested on PY Ta 714 in furniture inventories. The z-sign represents a dz/ts sound. torpedza → τράπεζα. "Trapeze" and "trapezoid" descend from this word (four-legged shape).'},
  {sylls:['ze','u','ke','si'],translit:'ze-u-ke-si',meaning:'Pairs / yokes (zeugesi)',classical:'ζεύγη',domain:'Objects',
   detail:'Dative plural of zeugos (pair, yoke). ze-u-ke-si = "with pairs/yokes". Related to Latin iugum and English "yoke". Appears in chariot and livestock records.'},
  {sylls:['ta','ra','nu'],translit:'ta-ra-nu',meaning:'Footstool (thranus)',classical:'θρῆνυς',domain:'Objects',
   detail:'Attested on PY Ta 722 in furniture inventories, often decorated with ivory inlay. Palaeolexicon: ta-ra-nu a-ja-me-no e-le-pa-te-jo = "footstool inlaid with ivory figures".'},
  // ── LAND & AGRICULTURE ───────────────────────────────
  {sylls:['te','me','no'],translit:'te-me-no',meaning:'Sacred land plot (temenos)',classical:'τέμενος',domain:'Land',
   detail:'Held by the wanax (30 units) and lawāgetās (10 units) in PY Er 312. The concept passed directly into Homer (Iliad 6.194) and later Greek religion.'},
  {sylls:['pe','ma'],translit:'pe-ma',meaning:'Seed / grain measure (sperma)',classical:'σπέρμα',domain:'Land',
   detail:'sp- dropped (scribal rule 9): sperma → pe-ma. Used to measure land value in the Er tablets: land is rated by the amount of seed-grain needed to sow it.'},
  {sylls:['ko','to','na'],translit:'ko-to-na',meaning:'Plot of land (ktoina)',classical:'κτοίνα',domain:'Land',
   detail:'The basic unit of land tenure. ko-to-na ki-ti-me-na = "cultivated plot"; ko-to-na ke-ke-me-na = "communal plot". The Eb/Ep tablets at Pylos are the most complex land records.'},
  {sylls:['a','ko','ro'],translit:'a-ko-ro',meaning:'Field (agros)',classical:'ἀγρός',domain:'Land',
   detail:'The open field, as opposed to the ko-to-na (plot). Ancestor of "agriculture", "agronomy". Appears in land tenure and livestock records.'},
  {sylls:['wo','ro','ki','jo','ne','jo'],translit:'wo-ro-ki-jo-ne-jo',meaning:'Of the Orgeones (a land category)',classical:'ὀργεών',domain:'Land',
   detail:'A specific type of communal or guild land in the Er tablets. The orgeones were religious associations holding land. PY Er 312: "wo-ro-ki-jo-ne-jo e-re-mo" = "desolate orgeone land".'},
  // ── OCCUPATIONS ──────────────────────────────────────
  {sylls:['po','me'],translit:'po-me',meaning:'Shepherd (poimēn)',classical:'ποιμήν',domain:'Occupations',
   detail:'The most common occupational title. The Cn series at Pylos tracks sheep, goats, and pigs. po-me-ne = dative "to the shepherd". Ancestor of "pastor" and "pastoral".'},
  {sylls:['ke','ra','me','u'],translit:'ke-ra-me-u',meaning:'Potter (kerameus)',classical:'κεραμεύς',domain:'Occupations',
   detail:'One of many craft titles. Ancestor of "ceramic". Appears in craft worker records. Other titles: ka-ke-u (bronze-smith), ku-ru-so-wo-ko (goldsmith).'},
  {sylls:['ka','ke','u'],translit:'ka-ke-u',meaning:'Bronze-smith (khalkeus)',classical:'χαλκεύς',domain:'Occupations',
   detail:'A bronze-working craftsman. ka-ke-we is the plural (khalkēwes = smiths). The PY Jn series is entirely about these workers — how much bronze each holds and owes.'},
  {sylls:['ku','ru','so','wo','ko'],translit:'ku-ru-so-wo-ko',meaning:'Goldsmith (khrusoworgos)',classical:'χρυσουργός',domain:'Occupations',
   detail:'Literally "gold-worker". wo-ko from worgos (worker, cf. ἔργον ergon). Attested in KN and PY records of luxury craftsmen attached to the palace.'},
  {sylls:['to','ko','so','wo','ko'],translit:'to-ko-so-wo-ko',meaning:'Bow-maker (toxoworgos)',classical:'τοξουργός',domain:'Occupations',
   detail:'Literally "bow-worker" — a maker of bows. to-ko-so = toxon (bow, the source of "toxic", originally "arrow poison"). Attested in military equipment records.'},
  {sylls:['a','ke','re','wa'],translit:'a-ke-re','meaning':'Collector (agerwan)',classical:'ἀγείρων',domain:'Occupations',
   detail:'An official who collects goods or taxes on behalf of the palace. The a-ke-re-wa appear in the Jn bronze records as recipients. Related to ἀγείρω (to gather).'},
  {sylls:['pu','te'],translit:'pu-te',meaning:'Planter (phutēr)',classical:'φυτήρ',domain:'Occupations',
   detail:'From phuteuō (to plant). pu-te-re is the plural. Appears in agricultural records. The aspiration is optionally marked: pu-te alongside phu-te-re in the tablets. Wikipedia Linear B.'},
  // ── PLACES ───────────────────────────────────────────
  {sylls:['pu','ro'],translit:'pu-ro',meaning:'Pylos',classical:'Πύλος',domain:'Places',
   detail:'The palace of Nestor on the western Peloponnese. 1107 tablets survive. Destroyed ~1180 BCE — the fire accidentally baked and preserved the clay. Excavated by Carl Blegen from 1939.'},
  {sylls:['ko','no','so'],translit:'ko-no-so',meaning:'Knossos',classical:'Κνωσός',domain:'Places',
   detail:'The great Minoan-Mycenaean palace on Crete. 3369 tablets — the largest archive. Double-s reduced to single (rule 6). Excavated by Arthur Evans 1900–1935.'},
  {sylls:['mu','ka','na'],translit:'mu-ka-na',meaning:'Mycenae (Mukānā)',classical:'Μυκῆναι',domain:'Places',
   detail:'The most powerful Bronze Age palace. Gave its name to the whole civilisation. Fewer tablets survive here — most records were on perishable materials.'},
  {sylls:['a','mi','ni','so'],translit:'a-mi-ni-so',meaning:'Amnisos (harbour of Knossos)',classical:'Ἀμνισός',domain:'Places',
   detail:'The harbour town near Knossos on Crete. Mentioned by Homer (Odyssey 19.188). Appears in Linear B as a receiving point for goods. Eileithyia (birth goddess) had a cave shrine there.'},
  {sylls:['ti','ri','to'],translit:'ti-ri-to',meaning:'Tiryns',classical:'Τίρυνς',domain:'Places',
   detail:'The great fortified palace in the Argolid. Linear B tablets found here. The massive "Cyclopean" walls still stand — they inspired the Greek legend that Cyclopes built them.'},
  {sylls:['za','ku','si','jo'],translit:'za-ku-si-jo',meaning:'Zakynthian / from Zakynthos',classical:'Ζακύνθιος',domain:'Places',
   detail:'An ethnic adjective attested in the tablets — referring to people or goods from the island of Zakynthos (modern Zante). Shows the range of Mycenaean trade contacts.'},
  // ── LANGUAGE & FORMULAS ──────────────────────────────
  {sylls:['to','so'],translit:'to-so',meaning:'So much / total (tosos)',classical:'τόσος',domain:'Formulas',
   detail:'The most important tally word. Introduces totals on accounting tablets. to-so-de = "and so many". to-sa = feminine form. Appears on virtually every accounting tablet.'},
  {sylls:['pa','ro'],translit:'pa-ro',meaning:'From / in the charge of (para)',classical:'παρά',domain:'Formulas',
   detail:'Very common header word preceding a name — indicates who holds the goods being recorded. pa-ro + name = "from [person]" or "in the keeping of [person]".'},
  {sylls:['o','pi'],translit:'o-pi',meaning:'In addition to / upon (epi)',classical:'ἐπί',domain:'Formulas',
   detail:'The preposition epi. o-pi-da-mi-jo = "community official" (epi + dāmos). Appears in quantities and additions.'},
  {sylls:['ne','wa'],translit:'ne-wa',meaning:'New (newos)',classical:'νέος',domain:'Formulas',
   detail:'Mycenaean newos → Attic neos (new). Appears in descriptions of equipment and vessels. The -w- (digamma) was lost in later Greek.'},
  {sylls:['me','zo'],translit:'me-zo',meaning:'Larger / greater (medzōs)',classical:'μείζων',domain:'Formulas',
   detail:'Comparative adjective. me-zo = medzōs > μείζων. The z-sign here represents a dz affricate. Attested on PY Ta 641 for "larger cups". Wikipedia Mycenaean Greek confirms.'},
  {sylls:['me','wi','jo'],translit:'me-wi-jo',meaning:'Smaller / lesser (mewios)',classical:'μείων',domain:'Formulas',
   detail:'Comparative adjective — the opposite of me-zo. me-wi-jo = mewios > μείων (smaller). Both used on PY Ta 641 to distinguish cup sizes. Antigone Journal confirms.'},
  {sylls:['za','we','te'],translit:'za-we-te',meaning:'This year (zawete)',classical:'(no direct heir)',domain:'Formulas',
   detail:'The only attested "year" expression. za-we-te-ro = "of this year" (genitive). The z-sign is a ts/dz affricate. Appears in seasonal records and offering schedules.'},
  {sylls:['do','so','mo'],translit:'do-so-mo',meaning:'Gift / offering (dosmos)',classical:'δόσμος',domain:'Formulas',
   detail:'From didōmi (to give). do-so-mo = an obligatory offering or tribute. PY Un 718: "sa-ra-pe-da po-se-da-o-ni do-so-mo" = "offerings for Poseidon of Srapedas".'},
];

// ── NUMBER SIGNS ─────────────────────────────────────────
const NUM_SIGNS = [
  {sign:'𐄇',val:1},{sign:'𐄈',val:2},{sign:'𐄉',val:3},{sign:'𐄊',val:4},
  {sign:'𐄋',val:5},{sign:'𐄌',val:6},{sign:'𐄍',val:7},{sign:'𐄎',val:8},{sign:'𐄏',val:9},
  {sign:'𐄙',val:10},{sign:'𐄚',val:20},{sign:'𐄛',val:30},{sign:'𐄜',val:40},
  {sign:'𐄝',val:50},{sign:'𐄞',val:60},{sign:'𐄟',val:70},{sign:'𐄠',val:80},{sign:'𐄡',val:90},
  {sign:'𐄢',val:100},{sign:'𐄣',val:200},{sign:'𐄦',val:500},
  {sign:'𐄫',val:1000},{sign:'𐄳',val:10000},
];

// ── SCRIBAL RULES ───────────────────────────────────────
const SCRIBAL_RULES = [
  {n:1,title:'Final consonants dropped',body:'Greek words end in consonants; Linear B signs end in vowels. The final consonant is omitted.',ex:'khalkos → ka-ko  |  patēr → pa-te  |  tripous → ti-ri-po'},
  {n:2,title:'Nasal before consonant omitted',body:'m or n before another consonant is silently dropped.',ex:'panta → pa-ta  |  anthropos → a-to-ro-qo'},
  {n:3,title:'Consonant clusters: echo-vowel rule',body:'Two consonants together get split with a dummy vowel matching the following syllable.',ex:'khrusos → ku-ru-so  |  Knossos → ko-no-so'},
  {n:4,title:'r and l are the same sign',body:'Linear B inherited no r/l distinction from Linear A.',ex:'eleutheros → e-re-u-te-ro  |  elaiwon → e-ra-wo'},
  {n:5,title:'No voiced / voiceless / aspirate distinction',body:'ka covers k, g, and kh. Only d vs t is distinguished.',ex:'ka-ko = khalkos (kh-)  |  do-e-ro = doelos (voiced d kept)'},
  {n:6,title:'Double consonants written single',body:'Geminates (ss, nn, etc.) are written once.',ex:'Knossos → ko-no-so  |  tosos → to-so'},
  {n:7,title:'w-series = digamma (Ϝ)',body:'Mycenaean had the digamma sound, lost in later dialects.',ex:'wanax → wa-na-ka  |  elaiwon → e-ra-wo (final -w)'},
  {n:8,title:'q-series = labio-velars (kʷ/gʷ)',body:'Proto-Greek labio-velars, later becoming p, b, or t.',ex:'kʷasileús → qa-si-re-u → basileus  |  gʷous → qo'},
  {n:9,title:'s before consonant dropped',body:'An s before another consonant is omitted.',ex:'sperma → pe-ma  |  stathmos → ta-to-mo'},
  {n:10,title:'Word divider: the vertical stroke',body:'A short vertical stroke separates words on tablets.',ex:'wa-na-ka , si-to [WHEAT] 30 = "the king: grain 30"'},
];

// ── I18N ────────────────────────────────────────────────
const I18N = {
  en:{
    lang:'EN',flag:'🇬🇧',
    nav_home:'Home',nav_syllabary:'Syllabary',nav_translit:'Transliterator',
    nav_tablets:'Tablets',nav_grammar:'Grammar',nav_vocab:'Vocabulary',
    nav_numbers:'Numbers',nav_quiz:'Quiz',nav_decode:'Decode',nav_translate:'Translator',
    hero_eyebrow:'c. 1450 – 1200 BCE · Mycenaean Greece',
    hero_tagline:'The earliest known writing system of the Greek language',
    select_sign:'Select a sign above to see details.',
    try:'Try:',score:'Score',correct:'Correct',total:'Total',streak:'Streak',
    next:'Next →',clear:'Clear',difficulty:'Difficulty',
    beginner:'Beginner',intermediate:'Intermediate',advanced:'Advanced',
    translate_placeholder:'Type an English, French or Greek word…',
    translate_hint:'e.g. king, honey, gold, ποιμήν, θεός, roi',
    no_translation:'No direct Mycenaean equivalent found.',
    no_translation_note:'Linear B only records ~2,000–3,000 words — mostly administrative vocabulary. Most modern concepts have no attested Mycenaean form.',
    found:'Found',tablets_title:'Real Tablets',tabs_cases:'Cases',tabs_decl:'Declensions',
    tabs_verbs:'Verbs',tabs_particles:'Particles & Formulae',tabs_scribal:'Scribal Rules',
  },
  fr:{
    lang:'FR',flag:'🇫🇷',
    nav_home:'Accueil',nav_syllabary:'Syllabaire',nav_translit:'Translittérateur',
    nav_tablets:'Tablettes',nav_grammar:'Grammaire',nav_vocab:'Vocabulaire',
    nav_numbers:'Nombres',nav_quiz:'Quiz',nav_decode:'Déchiffrer',nav_translate:'Traducteur',
    hero_eyebrow:'v. 1450 – 1200 av. J.-C. · Grèce mycénienne',
    hero_tagline:'Le plus ancien système d\'écriture connu de la langue grecque',
    select_sign:'Sélectionnez un signe pour voir les détails.',
    try:'Essayez :',score:'Score',correct:'Correct',total:'Total',streak:'Série',
    next:'Suivant →',clear:'Effacer',difficulty:'Difficulté',
    beginner:'Débutant',intermediate:'Intermédiaire',advanced:'Avancé',
    translate_placeholder:'Tapez un mot en anglais, français ou grec…',
    translate_hint:'ex : roi, miel, or, ποιμήν, θεός, king',
    no_translation:'Pas d\'équivalent mycénien direct trouvé.',
    no_translation_note:'Le Linéaire B ne contient que ~2 000–3 000 mots — surtout du vocabulaire administratif.',
    found:'Trouvé',tablets_title:'Tablettes réelles',tabs_cases:'Cas',tabs_decl:'Déclinaisons',
    tabs_verbs:'Verbes',tabs_particles:'Particules et formules',tabs_scribal:'Règles de scribes',
  },
  gr:{
    lang:'ΕΛ',flag:'🇬🇷',
    nav_home:'Αρχική',nav_syllabary:'Συλλαβάριο',nav_translit:'Μεταγραφέας',
    nav_tablets:'Πινακίδες',nav_grammar:'Γραμματική',nav_vocab:'Λεξιλόγιο',
    nav_numbers:'Αριθμοί',nav_quiz:'Κουίζ',nav_decode:'Αποκρυπτογράφηση',nav_translate:'Μεταφραστής',
    hero_eyebrow:'περ. 1450 – 1200 π.Χ. · Μυκηναϊκή Ελλάδα',
    hero_tagline:'Το αρχαιότερο γνωστό σύστημα γραφής της ελληνικής γλώσσας',
    select_sign:'Επιλέξτε ένα σημείο για λεπτομέρειες.',
    try:'Δοκιμάστε:',score:'Σκορ',correct:'Σωστό',total:'Σύνολο',streak:'Σερί',
    next:'Επόμενο →',clear:'Εκκαθάριση',difficulty:'Δυσκολία',
    beginner:'Αρχάριος',intermediate:'Ενδιάμεσο',advanced:'Προχωρημένο',
    translate_placeholder:'Πληκτρολογήστε λέξη στα αγγλικά, γαλλικά ή ελληνικά…',
    translate_hint:'π.χ. king, honey, gold, ποιμήν, θεός',
    no_translation:'Δεν βρέθηκε άμεσο μυκηναϊκό ισοδύναμο.',
    no_translation_note:'Η Γραμμική Β καταγράφει μόνο ~2.000–3.000 λέξεις — κυρίως διοικητικό λεξιλόγιο.',
    found:'Βρέθηκε',tablets_title:'Πραγματικές πινακίδες',tabs_cases:'Πτώσεις',tabs_decl:'Κλίσεις',
    tabs_verbs:'Ρήματα',tabs_particles:'Μόρια και φόρμουλες',tabs_scribal:'Γραφειοκρατικοί κανόνες',
  }
};

let LANG = (function(){try{return localStorage.getItem('lb_lang')||'en';}catch(e){return 'en';}}());
function t(k){return(I18N[LANG]&&I18N[LANG][k])||I18N.en[k]||k;}
function setLang(l){LANG=l;try{localStorage.setItem('lb_lang',l);}catch(e){}location.reload();}

function word(sylls){return sylls.map(s=>SIGNS[s]||'?').join('');}
function shuffle(arr){return[...arr].sort(()=>Math.random()-.5);}

function lookupTranslation(query){
  const q=query.toLowerCase().trim();
  if(!q)return null;
  return TRANSLATION_DICT.find(entry=>
    (entry.en&&entry.en.some(w=>w.toLowerCase()===q||q.includes(w.toLowerCase())||w.toLowerCase().includes(q)))||
    (entry.gr&&entry.gr.some(w=>w.toLowerCase()===q||q.includes(w.toLowerCase())))||
    (entry.fr&&entry.fr.some(w=>w.toLowerCase()===q||w.toLowerCase().includes(q)||q.includes(w.toLowerCase())))
  )||null;
}
